version: "3"

services:
  node:
    image: ritualnetwork/infernet-node:1.0.0-gpu
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./config.json:/app/config.json
      - ritual-node-logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    networks:
      - ritual
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    depends_on:
      - redis
    restart:
      on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_grace_period: 1m

  redis:
    image: redis:7.2.5-alpine
    expose:
      - "6379"
    networks:
      - ritual
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ritual-redis-data:/data
    restart:
      on-failure

  fluentbit:
    image: fluent/fluent-bit:3.0.6
    expose:
      - "24224"
    environment:
      - FLUENTBIT_CONFIG_PATH=/fluent-bit/etc/fluent-bit.conf
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log:ro
    networks:
      - ritual
    restart:
      on-failure

networks:
  ritual:

volumes:
  ritual-node-logs:
  ritual-redis-data:
